# Generated by Django 4.2.3 on 2023-08-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_yorummodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorummodel',
            name='yazi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='blog.yazilarmodel'),
        ),
    ]
